#-------------------------------
# General Site Settings
title: "Richelle Parra's Data Science Portfolio"
logo: icon-1.jpeg # You can add own logo.
description: "Richelle Parra's Data Science Portfolio & Resume Site"


#-------------------------------
# Author Settings
author:
  name: Richelle Parra
  image: Richelle_Parra_02.png
  say-hello: Hello! My name is <strong>Richelle Parra</strong>
  bio: Welcome to my data analysis portfolio & online resume site. Scroll down to find some of my <a href="https://rparra09.github.io/#anchor-name">sample data projects</a>. I have practical experience with data science tools, including Python and SQL, and machine learning methods including data cleaning, feature selection, model training and evaluation, and data visualization. In my leisure time, I enjoy <a href="https://www.youtube.com/results?search_query=lo+fi">Lo-Fi music</a> & <a href="https://rparra09.github.io/Interests/">running</a>.

      <li><a href="https://www.linkedin.com/in/richelleparra09/"><i class="ion ion-logo-linkedin"></i></a></li>
    

    
      <li><a href="https://github.com/rparra09"><i class="ion ion-logo-github"></i></a></li>
#-------------------------------
# Contact links
LinkedIn: https://www.linkedin.com/in/richelleparra09/ # Add your Linkedin handle



#-------------------------------
# Comment Section (Disqus)
#disqus-identifier:  # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
#instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
#instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
#mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
