#-------------------------------
# General Site Settings
title: Richelle's Data Analysis Portfolio
logo: icon-1.jpeg # You can add own logo.
description: Richelle's Data Analysis Portfolio


#-------------------------------
# Author Settings
author:
  name: Richelle Parra
  image: home-photo.jpg
  say-hello: Hello, I’m <strong>Richelle Parra</strong>
  bio: I study and design methods for <strong>data mining</strong>, <strong>data visualization</strong>, and how to extract <strong>business insights</strong> from data. 
  I enjoy <a href="https://www.youtube.com/results?search_query=lo+fi"> Lo-fi music</a> & running.


#-------------------------------
# Contact links
linkedin: https://www.linkedin.com/in/richelleparra09/ # Add your LinkedIn handle
github: https://github.com/rparra09 # Add your github handle

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: dame-mas # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: "#datascience" # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.
